# Generated by Django 5.1.3 on 2024-11-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomicSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenomicAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(max_length=50)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1)),
                ('qualifiers', models.JSONField(blank=True, null=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='data_analysis.genomicsequence')),
            ],
        ),
    ]
