# Generated by Django 5.1.3 on 2024-11-21 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('qualifiers', models.JSONField()),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='data_analysis.genomicsequence')),
            ],
        ),
    ]
