# Generated by Django 5.1.3 on 2024-11-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0002_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomicsequence',
            name='fna_file',
            field=models.FileField(blank=True, null=True, upload_to='genomic_sequences/fna/'),
        ),
        migrations.AddField(
            model_name='genomicsequence',
            name='gbff_file',
            field=models.FileField(blank=True, null=True, upload_to='genomic_sequences/gbff/'),
        ),
    ]
